#+TITLE: CSC 4110 Project README
#+AUTHOR: Ulysses Carlos, Jared Goldman
#+DATE:
#+OPTIONS: toc:nil
* CSC 4110 Project -- Rain Detector using a Raspberry Pi
This repository contains all the files needed to use a Raspberry Pi as a Rain Detector, which reports changes in local rain levels to a email server, as well as other options.
This project was led by Ulysses Carlos (myself) and Jared Goldman.
** Project Timeline

** Necessary Hardware
This project required the following hardware in order to work:
- Rain Sensor
- Float Sensor
- Graduated Cylinder 
- Raspberry Pi Zero W
** Necessary Software
*** TLDR;
If on Debian/Ubuntu/Raspbian, execute this command:
#+BEGIN_SRC bash
sudo apt-get install git postgresql libpq-dev libpqxx-dev cmake libcurl4-openssl-dev ncurses dialog libssl-dev
#+END_SRC
*** Long Explanation
Since this is a CLion Project, you can try installing it on your system and opening it, making sure to have the following components installed on your system. CLion comes with a version of CMake, but you need to install the following regardless:
**** Git
**** PostgreSQL with libpq and libpqxx >= 6
You can install all three on an Debian/Ubuntu/Raspbian using the following command:
#+BEGIN_SRC bash
sudo apt-get install postgresql libpq-dev libpqxx-dev
#+END_SRC
Please be aware that libpqxx-dev included with your package manager may be an older version, so you may have to [[https://github.com/jtv/libpqxx][compile from source]] to get the latest version.
If on macOS, you can install the packages using homebrew:
#+BEGIN_SRC bash
brew install postgresql
brew install libpq
brew install libpqxx
#+END_SRC
**** CMake >= 3.15 (If CLion cannot be installed on your system)
If on Debian/Ubuntu/Raspbian, use the following command:
#+BEGIN_SRC bash
sudo apt-get install cmake
#+END_SRC
On other Linux or UNIX Systems, you may need to use your package manager or [[https://cmake.org/download/][compile from source.]] You may also have to compile from source if your CMake version is less than 3.15.

**** libcurl-dev >= 7.50.0 with SSL.
To install libcurl-dev on Debian/Ubuntu/Raspbian, do
#+BEGIN_SRC bash
sudo apt-get install libcurl4-openssl-dev libssl-dev
#+END_SRC
Or use whatever package manager you have to install it.

In order to know if SSL is enabled within curl, do the following command:
#+BEGIN_SRC bash
curl-config --feature
#+END_SRC

You should see a list that should contain "SSL". If not, install a more recent version of libcurl through your package manager or [[https://curl.haxx.se/download.html][compile from source.]]
**** NCurses and Dialog Libraries
In order to display the text-based UI, NCurses and dialog must be installed on your system.
To do so, do
#+BEGIN_SRC bash
sudo apt-get install ncurses dialog
#+END_SRC
** Explanation 
** How to compile
If you can get CLion running on your machine, simply execute the program by pressing the run button on the top right (SHIFT-F10). If you can't get CLion (Or decide not to), run the following command in the project directory:
#+BEGIN_SRC sh
cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" .
make

#+END_SRC

** Example Usage
To run the program, do
#+BEGIN_SRC sh
./CSC4110_Project
#+END_SRC
** References
- [[https://computing.llnl.gov/tutorials/pthreads/][POSIX Thread Introduction]]
- [[https://www.cs.cmu.edu/afs/cs/academic/class/15492-f07/www/pthreads.html][POSIX Thread on C++]]
- [[https://curl.haxx.se/libcurl/c/][libcurl Documentation]]
- [[https://libpqxx.readthedocs.io/en/latest/][libpqxx Documentation]]



